// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using U2U.EntityFrameworkCore.TestData;

namespace U2U.EntityFrameworkCore.TestData.Migrations
{
    [DbContext(typeof(TrainingDb))]
    [Migration("20191030123636_Created")]
    partial class Created
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("U2U.EntityFrameworkCore.TestData.Course", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Code = "UARCH",
                            Name = "Patterns and Practices"
                        },
                        new
                        {
                            Code = "UWEBA",
                            Name = "Advanced Web Development"
                        },
                        new
                        {
                            Code = "UCORE",
                            Name = "Upgrade to DotNet Core"
                        },
                        new
                        {
                            Code = "UDEF",
                            Name = "Domain Driven Design With Entity Framework Core"
                        });
                });

            modelBuilder.Entity("U2U.EntityFrameworkCore.TestData.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("LoginId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            LoginId = 1,
                            Provider = "X",
                            StudentId = 1
                        },
                        new
                        {
                            LoginId = 2,
                            Provider = "X",
                            StudentId = 2
                        },
                        new
                        {
                            LoginId = 3,
                            Provider = "X",
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("U2U.EntityFrameworkCore.TestData.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionId");

                    b.HasIndex("Code");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            SessionId = 1,
                            Code = "UARCH",
                            EndDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2020, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SessionId = 2,
                            Code = "UWEBA",
                            EndDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2020, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SessionId = 3,
                            Code = "UCORE",
                            EndDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2020, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("U2U.EntityFrameworkCore.TestData.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Joske",
                            LastName = "Vermeulen"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Eddy",
                            LastName = "Wally"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Sam",
                            LastName = "Goris"
                        });
                });

            modelBuilder.Entity("U2U.EntityFrameworkCore.TestData.StudentSession", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("SessionId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentSession");
                });

            modelBuilder.Entity("U2U.EntityFrameworkCore.TestData.Login", b =>
                {
                    b.HasOne("U2U.EntityFrameworkCore.TestData.Student", "Student")
                        .WithOne("Login")
                        .HasForeignKey("U2U.EntityFrameworkCore.TestData.Login", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("U2U.EntityFrameworkCore.TestData.Session", b =>
                {
                    b.HasOne("U2U.EntityFrameworkCore.TestData.Course", "Course")
                        .WithMany("Sessions")
                        .HasForeignKey("Code");
                });

            modelBuilder.Entity("U2U.EntityFrameworkCore.TestData.StudentSession", b =>
                {
                    b.HasOne("U2U.EntityFrameworkCore.TestData.Session", "Session")
                        .WithMany("Students")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("U2U.EntityFrameworkCore.TestData.Student", "Student")
                        .WithMany("Sessions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
