# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_run:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish U2U.EntityFrameworkCore.Abstractions
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/U2U.EntityFrameworkCore.Abstractions/U2U.EntityFrameworkCore.Abstractions.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish U2U.EntityFrameworkCore
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/U2U.EntityFrameworkCore/U2U.EntityFrameworkCore.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish U2U.EntityFrameworkCore.Testing
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/U2U.EntityFrameworkCore.Testing/U2U.EntityFrameworkCore.Testing.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
